version: "3.8"

services:
  electrumx:
    build: .
    container_name: electrumx
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./db:/db
    ports:
      - "50001:50001"  # TCP
      - "50002:50002"  # SSL
    environment:
      - COIN=BitcoinGold
      - DB_DIRECTORY=/db
      - DAEMON_URL=http://username:password@hostname:port/
      - SERVICES=tcp://:50001,ssl://:50002
      - ALLOW_ROOT=true
      - DB_ENGINE=rocksdb
      - MAX_SEND=10000000
      - BANDWIDTH_UNIT_COST=50000
      - CACHE_MB=2000
      # Optional SSL configuration
      # - SSL_CERTFILE=/path/to/certfile.crt
      # - SSL_KEYFILE=/path/to/keyfile.key
    networks:
      - electrum_network

networks:
  electrum_network:
    driver: bridge 